name: 3806ICT
channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - scipy
  - stable-baselines3
  - pandas
  - matplotlib
  - seaborn
  - jupyterlab
  - compilers
  - gymnasium
  - scikit-learn
  - pytorch
  - torchvision
  - pip
