// Generated by gencpp from file assignment3/CollectDataRequest.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT3_MESSAGE_COLLECTDATAREQUEST_H
#define ASSIGNMENT3_MESSAGE_COLLECTDATAREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignment3
{
template <class ContainerAllocator>
struct CollectDataRequest_
{
  typedef CollectDataRequest_<ContainerAllocator> Type;

  CollectDataRequest_()
    {
    }
  CollectDataRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::assignment3::CollectDataRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment3::CollectDataRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CollectDataRequest_

typedef ::assignment3::CollectDataRequest_<std::allocator<void> > CollectDataRequest;

typedef boost::shared_ptr< ::assignment3::CollectDataRequest > CollectDataRequestPtr;
typedef boost::shared_ptr< ::assignment3::CollectDataRequest const> CollectDataRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment3::CollectDataRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment3::CollectDataRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace assignment3

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assignment3::CollectDataRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment3::CollectDataRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment3::CollectDataRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment3::CollectDataRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment3::CollectDataRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment3::CollectDataRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment3::CollectDataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::assignment3::CollectDataRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment3::CollectDataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment3/CollectDataRequest";
  }

  static const char* value(const ::assignment3::CollectDataRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment3::CollectDataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::assignment3::CollectDataRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment3::CollectDataRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CollectDataRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment3::CollectDataRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::assignment3::CollectDataRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT3_MESSAGE_COLLECTDATAREQUEST_H
