// Generated by gencpp from file assignment3/CollectData.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT3_MESSAGE_COLLECTDATA_H
#define ASSIGNMENT3_MESSAGE_COLLECTDATA_H

#include <ros/service_traits.h>


#include <assignment3/CollectDataRequest.h>
#include <assignment3/CollectDataResponse.h>


namespace assignment3
{

struct CollectData
{

typedef CollectDataRequest Request;
typedef CollectDataResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CollectData
} // namespace assignment3


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::assignment3::CollectData > {
  static const char* value()
  {
    return "0b05c236c4d2e3f6f6d7b02102165372";
  }

  static const char* value(const ::assignment3::CollectData&) { return value(); }
};

template<>
struct DataType< ::assignment3::CollectData > {
  static const char* value()
  {
    return "assignment3/CollectData";
  }

  static const char* value(const ::assignment3::CollectData&) { return value(); }
};


// service_traits::MD5Sum< ::assignment3::CollectDataRequest> should match
// service_traits::MD5Sum< ::assignment3::CollectData >
template<>
struct MD5Sum< ::assignment3::CollectDataRequest>
{
  static const char* value()
  {
    return MD5Sum< ::assignment3::CollectData >::value();
  }
  static const char* value(const ::assignment3::CollectDataRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment3::CollectDataRequest> should match
// service_traits::DataType< ::assignment3::CollectData >
template<>
struct DataType< ::assignment3::CollectDataRequest>
{
  static const char* value()
  {
    return DataType< ::assignment3::CollectData >::value();
  }
  static const char* value(const ::assignment3::CollectDataRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::assignment3::CollectDataResponse> should match
// service_traits::MD5Sum< ::assignment3::CollectData >
template<>
struct MD5Sum< ::assignment3::CollectDataResponse>
{
  static const char* value()
  {
    return MD5Sum< ::assignment3::CollectData >::value();
  }
  static const char* value(const ::assignment3::CollectDataResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment3::CollectDataResponse> should match
// service_traits::DataType< ::assignment3::CollectData >
template<>
struct DataType< ::assignment3::CollectDataResponse>
{
  static const char* value()
  {
    return DataType< ::assignment3::CollectData >::value();
  }
  static const char* value(const ::assignment3::CollectDataResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASSIGNMENT3_MESSAGE_COLLECTDATA_H
