// Generated by gencpp from file assignment3/Command.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT3_MESSAGE_COMMAND_H
#define ASSIGNMENT3_MESSAGE_COMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace assignment3
{
template <class ContainerAllocator>
struct Command_
{
  typedef Command_<ContainerAllocator> Type;

  Command_()
    : target_position()
    , target_speed(0.0)  {
    }
  Command_(const ContainerAllocator& _alloc)
    : target_position(_alloc)
    , target_speed(0.0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _target_position_type;
  _target_position_type target_position;

   typedef float _target_speed_type;
  _target_speed_type target_speed;





  typedef boost::shared_ptr< ::assignment3::Command_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment3::Command_<ContainerAllocator> const> ConstPtr;

}; // struct Command_

typedef ::assignment3::Command_<std::allocator<void> > Command;

typedef boost::shared_ptr< ::assignment3::Command > CommandPtr;
typedef boost::shared_ptr< ::assignment3::Command const> CommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment3::Command_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment3::Command_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assignment3::Command_<ContainerAllocator1> & lhs, const ::assignment3::Command_<ContainerAllocator2> & rhs)
{
  return lhs.target_position == rhs.target_position &&
    lhs.target_speed == rhs.target_speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assignment3::Command_<ContainerAllocator1> & lhs, const ::assignment3::Command_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assignment3

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assignment3::Command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment3::Command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment3::Command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment3::Command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment3::Command_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment3::Command_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment3::Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b6e48e0f01c18d28e055fd89413db754";
  }

  static const char* value(const ::assignment3::Command_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb6e48e0f01c18d28ULL;
  static const uint64_t static_value2 = 0xe055fd89413db754ULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment3::Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment3/Command";
  }

  static const char* value(const ::assignment3::Command_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment3::Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point target_position\n"
"float32 target_speed\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::assignment3::Command_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment3::Command_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target_position);
      stream.next(m.target_speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Command_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment3::Command_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment3::Command_<ContainerAllocator>& v)
  {
    s << indent << "target_position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.target_position);
    s << indent << "target_speed: ";
    Printer<float>::stream(s, indent + "  ", v.target_speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT3_MESSAGE_COMMAND_H
