// Generated by gencpp from file assignment3/CreatePlanRequest.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT3_MESSAGE_CREATEPLANREQUEST_H
#define ASSIGNMENT3_MESSAGE_CREATEPLANREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <assignment3/State.h>
#include <assignment3/Goals.h>

namespace assignment3
{
template <class ContainerAllocator>
struct CreatePlanRequest_
{
  typedef CreatePlanRequest_<ContainerAllocator> Type;

  CreatePlanRequest_()
    : state()
    , goals()  {
    }
  CreatePlanRequest_(const ContainerAllocator& _alloc)
    : state(_alloc)
    , goals(_alloc)  {
  (void)_alloc;
    }



   typedef  ::assignment3::State_<ContainerAllocator>  _state_type;
  _state_type state;

   typedef  ::assignment3::Goals_<ContainerAllocator>  _goals_type;
  _goals_type goals;





  typedef boost::shared_ptr< ::assignment3::CreatePlanRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment3::CreatePlanRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CreatePlanRequest_

typedef ::assignment3::CreatePlanRequest_<std::allocator<void> > CreatePlanRequest;

typedef boost::shared_ptr< ::assignment3::CreatePlanRequest > CreatePlanRequestPtr;
typedef boost::shared_ptr< ::assignment3::CreatePlanRequest const> CreatePlanRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment3::CreatePlanRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment3::CreatePlanRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assignment3::CreatePlanRequest_<ContainerAllocator1> & lhs, const ::assignment3::CreatePlanRequest_<ContainerAllocator2> & rhs)
{
  return lhs.state == rhs.state &&
    lhs.goals == rhs.goals;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assignment3::CreatePlanRequest_<ContainerAllocator1> & lhs, const ::assignment3::CreatePlanRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assignment3

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assignment3::CreatePlanRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment3::CreatePlanRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment3::CreatePlanRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment3::CreatePlanRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment3::CreatePlanRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment3::CreatePlanRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment3::CreatePlanRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "26f4b76bd097e1b1edcbe52b3102526a";
  }

  static const char* value(const ::assignment3::CreatePlanRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x26f4b76bd097e1b1ULL;
  static const uint64_t static_value2 = 0xedcbe52b3102526aULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment3::CreatePlanRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment3/CreatePlanRequest";
  }

  static const char* value(const ::assignment3::CreatePlanRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment3::CreatePlanRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "State state\n"
"Goals goals\n"
"\n"
"================================================================================\n"
"MSG: assignment3/State\n"
"geometry_msgs/Point current_position\n"
"Map environment_map\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: assignment3/Map\n"
"geometry_msgs/Point[] obstacle_positions\n"
"\n"
"================================================================================\n"
"MSG: assignment3/Goals\n"
"Goal[] primary_goals\n"
"Goal[] secondary_goals\n"
"\n"
"================================================================================\n"
"MSG: assignment3/Goal\n"
"string description\n"
"int32 priority\n"
"geometry_msgs/Point[] waypoints\n"
;
  }

  static const char* value(const ::assignment3::CreatePlanRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment3::CreatePlanRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
      stream.next(m.goals);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CreatePlanRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment3::CreatePlanRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment3::CreatePlanRequest_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    s << std::endl;
    Printer< ::assignment3::State_<ContainerAllocator> >::stream(s, indent + "  ", v.state);
    s << indent << "goals: ";
    s << std::endl;
    Printer< ::assignment3::Goals_<ContainerAllocator> >::stream(s, indent + "  ", v.goals);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT3_MESSAGE_CREATEPLANREQUEST_H
