// Generated by gencpp from file assignment3/ExecutePlanRequest.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT3_MESSAGE_EXECUTEPLANREQUEST_H
#define ASSIGNMENT3_MESSAGE_EXECUTEPLANREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <assignment3/Plan.h>

namespace assignment3
{
template <class ContainerAllocator>
struct ExecutePlanRequest_
{
  typedef ExecutePlanRequest_<ContainerAllocator> Type;

  ExecutePlanRequest_()
    : plan()  {
    }
  ExecutePlanRequest_(const ContainerAllocator& _alloc)
    : plan(_alloc)  {
  (void)_alloc;
    }



   typedef  ::assignment3::Plan_<ContainerAllocator>  _plan_type;
  _plan_type plan;





  typedef boost::shared_ptr< ::assignment3::ExecutePlanRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment3::ExecutePlanRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ExecutePlanRequest_

typedef ::assignment3::ExecutePlanRequest_<std::allocator<void> > ExecutePlanRequest;

typedef boost::shared_ptr< ::assignment3::ExecutePlanRequest > ExecutePlanRequestPtr;
typedef boost::shared_ptr< ::assignment3::ExecutePlanRequest const> ExecutePlanRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment3::ExecutePlanRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment3::ExecutePlanRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assignment3::ExecutePlanRequest_<ContainerAllocator1> & lhs, const ::assignment3::ExecutePlanRequest_<ContainerAllocator2> & rhs)
{
  return lhs.plan == rhs.plan;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assignment3::ExecutePlanRequest_<ContainerAllocator1> & lhs, const ::assignment3::ExecutePlanRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assignment3

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assignment3::ExecutePlanRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment3::ExecutePlanRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment3::ExecutePlanRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment3::ExecutePlanRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment3::ExecutePlanRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment3::ExecutePlanRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment3::ExecutePlanRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b47c1e2e43b70f5255aaf39cf4bfdf46";
  }

  static const char* value(const ::assignment3::ExecutePlanRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb47c1e2e43b70f52ULL;
  static const uint64_t static_value2 = 0x55aaf39cf4bfdf46ULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment3::ExecutePlanRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment3/ExecutePlanRequest";
  }

  static const char* value(const ::assignment3::ExecutePlanRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment3::ExecutePlanRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Plan plan\n"
"\n"
"================================================================================\n"
"MSG: assignment3/Plan\n"
"Waypoint[] waypoints\n"
"\n"
"================================================================================\n"
"MSG: assignment3/Waypoint\n"
"geometry_msgs/Point position\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::assignment3::ExecutePlanRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment3::ExecutePlanRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.plan);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExecutePlanRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment3::ExecutePlanRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment3::ExecutePlanRequest_<ContainerAllocator>& v)
  {
    s << indent << "plan: ";
    s << std::endl;
    Printer< ::assignment3::Plan_<ContainerAllocator> >::stream(s, indent + "  ", v.plan);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT3_MESSAGE_EXECUTEPLANREQUEST_H
