// Generated by gencpp from file assignment3/ExecutePlan.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT3_MESSAGE_EXECUTEPLAN_H
#define ASSIGNMENT3_MESSAGE_EXECUTEPLAN_H

#include <ros/service_traits.h>


#include <assignment3/ExecutePlanRequest.h>
#include <assignment3/ExecutePlanResponse.h>


namespace assignment3
{

struct ExecutePlan
{

typedef ExecutePlanRequest Request;
typedef ExecutePlanResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ExecutePlan
} // namespace assignment3


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::assignment3::ExecutePlan > {
  static const char* value()
  {
    return "eaee7ab4e67b6b1fb802cc08dec8e9d9";
  }

  static const char* value(const ::assignment3::ExecutePlan&) { return value(); }
};

template<>
struct DataType< ::assignment3::ExecutePlan > {
  static const char* value()
  {
    return "assignment3/ExecutePlan";
  }

  static const char* value(const ::assignment3::ExecutePlan&) { return value(); }
};


// service_traits::MD5Sum< ::assignment3::ExecutePlanRequest> should match
// service_traits::MD5Sum< ::assignment3::ExecutePlan >
template<>
struct MD5Sum< ::assignment3::ExecutePlanRequest>
{
  static const char* value()
  {
    return MD5Sum< ::assignment3::ExecutePlan >::value();
  }
  static const char* value(const ::assignment3::ExecutePlanRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment3::ExecutePlanRequest> should match
// service_traits::DataType< ::assignment3::ExecutePlan >
template<>
struct DataType< ::assignment3::ExecutePlanRequest>
{
  static const char* value()
  {
    return DataType< ::assignment3::ExecutePlan >::value();
  }
  static const char* value(const ::assignment3::ExecutePlanRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::assignment3::ExecutePlanResponse> should match
// service_traits::MD5Sum< ::assignment3::ExecutePlan >
template<>
struct MD5Sum< ::assignment3::ExecutePlanResponse>
{
  static const char* value()
  {
    return MD5Sum< ::assignment3::ExecutePlan >::value();
  }
  static const char* value(const ::assignment3::ExecutePlanResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment3::ExecutePlanResponse> should match
// service_traits::DataType< ::assignment3::ExecutePlan >
template<>
struct DataType< ::assignment3::ExecutePlanResponse>
{
  static const char* value()
  {
    return DataType< ::assignment3::ExecutePlan >::value();
  }
  static const char* value(const ::assignment3::ExecutePlanResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASSIGNMENT3_MESSAGE_EXECUTEPLAN_H
