// Generated by gencpp from file assignment3/ExecutePlanResponse.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT3_MESSAGE_EXECUTEPLANRESPONSE_H
#define ASSIGNMENT3_MESSAGE_EXECUTEPLANRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignment3
{
template <class ContainerAllocator>
struct ExecutePlanResponse_
{
  typedef ExecutePlanResponse_<ContainerAllocator> Type;

  ExecutePlanResponse_()
    : success(false)  {
    }
  ExecutePlanResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::assignment3::ExecutePlanResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment3::ExecutePlanResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ExecutePlanResponse_

typedef ::assignment3::ExecutePlanResponse_<std::allocator<void> > ExecutePlanResponse;

typedef boost::shared_ptr< ::assignment3::ExecutePlanResponse > ExecutePlanResponsePtr;
typedef boost::shared_ptr< ::assignment3::ExecutePlanResponse const> ExecutePlanResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment3::ExecutePlanResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment3::ExecutePlanResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assignment3::ExecutePlanResponse_<ContainerAllocator1> & lhs, const ::assignment3::ExecutePlanResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assignment3::ExecutePlanResponse_<ContainerAllocator1> & lhs, const ::assignment3::ExecutePlanResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assignment3

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assignment3::ExecutePlanResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment3::ExecutePlanResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment3::ExecutePlanResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment3::ExecutePlanResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment3::ExecutePlanResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment3::ExecutePlanResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment3::ExecutePlanResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::assignment3::ExecutePlanResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment3::ExecutePlanResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment3/ExecutePlanResponse";
  }

  static const char* value(const ::assignment3::ExecutePlanResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment3::ExecutePlanResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"\n"
;
  }

  static const char* value(const ::assignment3::ExecutePlanResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment3::ExecutePlanResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExecutePlanResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment3::ExecutePlanResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment3::ExecutePlanResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT3_MESSAGE_EXECUTEPLANRESPONSE_H
