// Generated by gencpp from file assignment3/Feedback.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT3_MESSAGE_FEEDBACK_H
#define ASSIGNMENT3_MESSAGE_FEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignment3
{
template <class ContainerAllocator>
struct Feedback_
{
  typedef Feedback_<ContainerAllocator> Type;

  Feedback_()
    : action_success(false)  {
    }
  Feedback_(const ContainerAllocator& _alloc)
    : action_success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _action_success_type;
  _action_success_type action_success;





  typedef boost::shared_ptr< ::assignment3::Feedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment3::Feedback_<ContainerAllocator> const> ConstPtr;

}; // struct Feedback_

typedef ::assignment3::Feedback_<std::allocator<void> > Feedback;

typedef boost::shared_ptr< ::assignment3::Feedback > FeedbackPtr;
typedef boost::shared_ptr< ::assignment3::Feedback const> FeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment3::Feedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment3::Feedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assignment3::Feedback_<ContainerAllocator1> & lhs, const ::assignment3::Feedback_<ContainerAllocator2> & rhs)
{
  return lhs.action_success == rhs.action_success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assignment3::Feedback_<ContainerAllocator1> & lhs, const ::assignment3::Feedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assignment3

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assignment3::Feedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment3::Feedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment3::Feedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment3::Feedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment3::Feedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment3::Feedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment3::Feedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f80c0f2f2bc7be57a86c32c39edc051b";
  }

  static const char* value(const ::assignment3::Feedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf80c0f2f2bc7be57ULL;
  static const uint64_t static_value2 = 0xa86c32c39edc051bULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment3::Feedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment3/Feedback";
  }

  static const char* value(const ::assignment3::Feedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment3::Feedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool action_success\n"
;
  }

  static const char* value(const ::assignment3::Feedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment3::Feedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action_success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Feedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment3::Feedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment3::Feedback_<ContainerAllocator>& v)
  {
    s << indent << "action_success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.action_success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT3_MESSAGE_FEEDBACK_H
