// Generated by gencpp from file assignment3/Obstacle.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT3_MESSAGE_OBSTACLE_H
#define ASSIGNMENT3_MESSAGE_OBSTACLE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace assignment3
{
template <class ContainerAllocator>
struct Obstacle_
{
  typedef Obstacle_<ContainerAllocator> Type;

  Obstacle_()
    : position()
    , size(0.0)  {
    }
  Obstacle_(const ContainerAllocator& _alloc)
    : position(_alloc)
    , size(0.0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef float _size_type;
  _size_type size;





  typedef boost::shared_ptr< ::assignment3::Obstacle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment3::Obstacle_<ContainerAllocator> const> ConstPtr;

}; // struct Obstacle_

typedef ::assignment3::Obstacle_<std::allocator<void> > Obstacle;

typedef boost::shared_ptr< ::assignment3::Obstacle > ObstaclePtr;
typedef boost::shared_ptr< ::assignment3::Obstacle const> ObstacleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment3::Obstacle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment3::Obstacle_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assignment3::Obstacle_<ContainerAllocator1> & lhs, const ::assignment3::Obstacle_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position &&
    lhs.size == rhs.size;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assignment3::Obstacle_<ContainerAllocator1> & lhs, const ::assignment3::Obstacle_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assignment3

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assignment3::Obstacle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment3::Obstacle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment3::Obstacle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment3::Obstacle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment3::Obstacle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment3::Obstacle_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment3::Obstacle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "726a1872b6a225d0af03b0427f4f8d20";
  }

  static const char* value(const ::assignment3::Obstacle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x726a1872b6a225d0ULL;
  static const uint64_t static_value2 = 0xaf03b0427f4f8d20ULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment3::Obstacle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment3/Obstacle";
  }

  static const char* value(const ::assignment3::Obstacle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment3::Obstacle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point position\n"
"float32 size\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::assignment3::Obstacle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment3::Obstacle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.size);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Obstacle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment3::Obstacle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment3::Obstacle_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "size: ";
    Printer<float>::stream(s, indent + "  ", v.size);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT3_MESSAGE_OBSTACLE_H
