// Generated by gencpp from file assignment3/ProcessSensorDataResponse.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT3_MESSAGE_PROCESSSENSORDATARESPONSE_H
#define ASSIGNMENT3_MESSAGE_PROCESSSENSORDATARESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <assignment3/State.h>

namespace assignment3
{
template <class ContainerAllocator>
struct ProcessSensorDataResponse_
{
  typedef ProcessSensorDataResponse_<ContainerAllocator> Type;

  ProcessSensorDataResponse_()
    : state()  {
    }
  ProcessSensorDataResponse_(const ContainerAllocator& _alloc)
    : state(_alloc)  {
  (void)_alloc;
    }



   typedef  ::assignment3::State_<ContainerAllocator>  _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::assignment3::ProcessSensorDataResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment3::ProcessSensorDataResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ProcessSensorDataResponse_

typedef ::assignment3::ProcessSensorDataResponse_<std::allocator<void> > ProcessSensorDataResponse;

typedef boost::shared_ptr< ::assignment3::ProcessSensorDataResponse > ProcessSensorDataResponsePtr;
typedef boost::shared_ptr< ::assignment3::ProcessSensorDataResponse const> ProcessSensorDataResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment3::ProcessSensorDataResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment3::ProcessSensorDataResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assignment3::ProcessSensorDataResponse_<ContainerAllocator1> & lhs, const ::assignment3::ProcessSensorDataResponse_<ContainerAllocator2> & rhs)
{
  return lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assignment3::ProcessSensorDataResponse_<ContainerAllocator1> & lhs, const ::assignment3::ProcessSensorDataResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assignment3

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assignment3::ProcessSensorDataResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment3::ProcessSensorDataResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment3::ProcessSensorDataResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment3::ProcessSensorDataResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment3::ProcessSensorDataResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment3::ProcessSensorDataResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment3::ProcessSensorDataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d35b1d9d2b5ea96b7efa33218831c8f0";
  }

  static const char* value(const ::assignment3::ProcessSensorDataResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd35b1d9d2b5ea96bULL;
  static const uint64_t static_value2 = 0x7efa33218831c8f0ULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment3::ProcessSensorDataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment3/ProcessSensorDataResponse";
  }

  static const char* value(const ::assignment3::ProcessSensorDataResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment3::ProcessSensorDataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "State state\n"
"\n"
"\n"
"================================================================================\n"
"MSG: assignment3/State\n"
"geometry_msgs/Point current_position\n"
"Map environment_map\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: assignment3/Map\n"
"geometry_msgs/Point[] obstacle_positions\n"
;
  }

  static const char* value(const ::assignment3::ProcessSensorDataResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment3::ProcessSensorDataResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ProcessSensorDataResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment3::ProcessSensorDataResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment3::ProcessSensorDataResponse_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    s << std::endl;
    Printer< ::assignment3::State_<ContainerAllocator> >::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT3_MESSAGE_PROCESSSENSORDATARESPONSE_H
