// Generated by gencpp from file assignment3/ProcessSensorData.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT3_MESSAGE_PROCESSSENSORDATA_H
#define ASSIGNMENT3_MESSAGE_PROCESSSENSORDATA_H

#include <ros/service_traits.h>


#include <assignment3/ProcessSensorDataRequest.h>
#include <assignment3/ProcessSensorDataResponse.h>


namespace assignment3
{

struct ProcessSensorData
{

typedef ProcessSensorDataRequest Request;
typedef ProcessSensorDataResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ProcessSensorData
} // namespace assignment3


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::assignment3::ProcessSensorData > {
  static const char* value()
  {
    return "c62a3bb50e5a12b840b3112c4065ba79";
  }

  static const char* value(const ::assignment3::ProcessSensorData&) { return value(); }
};

template<>
struct DataType< ::assignment3::ProcessSensorData > {
  static const char* value()
  {
    return "assignment3/ProcessSensorData";
  }

  static const char* value(const ::assignment3::ProcessSensorData&) { return value(); }
};


// service_traits::MD5Sum< ::assignment3::ProcessSensorDataRequest> should match
// service_traits::MD5Sum< ::assignment3::ProcessSensorData >
template<>
struct MD5Sum< ::assignment3::ProcessSensorDataRequest>
{
  static const char* value()
  {
    return MD5Sum< ::assignment3::ProcessSensorData >::value();
  }
  static const char* value(const ::assignment3::ProcessSensorDataRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment3::ProcessSensorDataRequest> should match
// service_traits::DataType< ::assignment3::ProcessSensorData >
template<>
struct DataType< ::assignment3::ProcessSensorDataRequest>
{
  static const char* value()
  {
    return DataType< ::assignment3::ProcessSensorData >::value();
  }
  static const char* value(const ::assignment3::ProcessSensorDataRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::assignment3::ProcessSensorDataResponse> should match
// service_traits::MD5Sum< ::assignment3::ProcessSensorData >
template<>
struct MD5Sum< ::assignment3::ProcessSensorDataResponse>
{
  static const char* value()
  {
    return MD5Sum< ::assignment3::ProcessSensorData >::value();
  }
  static const char* value(const ::assignment3::ProcessSensorDataResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment3::ProcessSensorDataResponse> should match
// service_traits::DataType< ::assignment3::ProcessSensorData >
template<>
struct DataType< ::assignment3::ProcessSensorDataResponse>
{
  static const char* value()
  {
    return DataType< ::assignment3::ProcessSensorData >::value();
  }
  static const char* value(const ::assignment3::ProcessSensorDataResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASSIGNMENT3_MESSAGE_PROCESSSENSORDATA_H
