// Generated by gencpp from file assignment3/State.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT3_MESSAGE_STATE_H
#define ASSIGNMENT3_MESSAGE_STATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <assignment3/Map.h>

namespace assignment3
{
template <class ContainerAllocator>
struct State_
{
  typedef State_<ContainerAllocator> Type;

  State_()
    : current_position()
    , environment_map()  {
    }
  State_(const ContainerAllocator& _alloc)
    : current_position(_alloc)
    , environment_map(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _current_position_type;
  _current_position_type current_position;

   typedef  ::assignment3::Map_<ContainerAllocator>  _environment_map_type;
  _environment_map_type environment_map;





  typedef boost::shared_ptr< ::assignment3::State_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment3::State_<ContainerAllocator> const> ConstPtr;

}; // struct State_

typedef ::assignment3::State_<std::allocator<void> > State;

typedef boost::shared_ptr< ::assignment3::State > StatePtr;
typedef boost::shared_ptr< ::assignment3::State const> StateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment3::State_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment3::State_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assignment3::State_<ContainerAllocator1> & lhs, const ::assignment3::State_<ContainerAllocator2> & rhs)
{
  return lhs.current_position == rhs.current_position &&
    lhs.environment_map == rhs.environment_map;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assignment3::State_<ContainerAllocator1> & lhs, const ::assignment3::State_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assignment3

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assignment3::State_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment3::State_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment3::State_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment3::State_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment3::State_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment3::State_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment3::State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9ed7a5ab0f77624d96ff4cc104c195a8";
  }

  static const char* value(const ::assignment3::State_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9ed7a5ab0f77624dULL;
  static const uint64_t static_value2 = 0x96ff4cc104c195a8ULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment3::State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment3/State";
  }

  static const char* value(const ::assignment3::State_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment3::State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point current_position\n"
"Map environment_map\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: assignment3/Map\n"
"geometry_msgs/Point[] obstacle_positions\n"
;
  }

  static const char* value(const ::assignment3::State_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment3::State_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current_position);
      stream.next(m.environment_map);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct State_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment3::State_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment3::State_<ContainerAllocator>& v)
  {
    s << indent << "current_position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.current_position);
    s << indent << "environment_map: ";
    s << std::endl;
    Printer< ::assignment3::Map_<ContainerAllocator> >::stream(s, indent + "  ", v.environment_map);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT3_MESSAGE_STATE_H
