// Generated by gencpp from file assignment3/UpdateGoalsResponse.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT3_MESSAGE_UPDATEGOALSRESPONSE_H
#define ASSIGNMENT3_MESSAGE_UPDATEGOALSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <assignment3/Goals.h>

namespace assignment3
{
template <class ContainerAllocator>
struct UpdateGoalsResponse_
{
  typedef UpdateGoalsResponse_<ContainerAllocator> Type;

  UpdateGoalsResponse_()
    : goals()  {
    }
  UpdateGoalsResponse_(const ContainerAllocator& _alloc)
    : goals(_alloc)  {
  (void)_alloc;
    }



   typedef  ::assignment3::Goals_<ContainerAllocator>  _goals_type;
  _goals_type goals;





  typedef boost::shared_ptr< ::assignment3::UpdateGoalsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment3::UpdateGoalsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct UpdateGoalsResponse_

typedef ::assignment3::UpdateGoalsResponse_<std::allocator<void> > UpdateGoalsResponse;

typedef boost::shared_ptr< ::assignment3::UpdateGoalsResponse > UpdateGoalsResponsePtr;
typedef boost::shared_ptr< ::assignment3::UpdateGoalsResponse const> UpdateGoalsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment3::UpdateGoalsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment3::UpdateGoalsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assignment3::UpdateGoalsResponse_<ContainerAllocator1> & lhs, const ::assignment3::UpdateGoalsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.goals == rhs.goals;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assignment3::UpdateGoalsResponse_<ContainerAllocator1> & lhs, const ::assignment3::UpdateGoalsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assignment3

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assignment3::UpdateGoalsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment3::UpdateGoalsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment3::UpdateGoalsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment3::UpdateGoalsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment3::UpdateGoalsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment3::UpdateGoalsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment3::UpdateGoalsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c98f3dbea20dbea9abe774fb6d094aa4";
  }

  static const char* value(const ::assignment3::UpdateGoalsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc98f3dbea20dbea9ULL;
  static const uint64_t static_value2 = 0xabe774fb6d094aa4ULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment3::UpdateGoalsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment3/UpdateGoalsResponse";
  }

  static const char* value(const ::assignment3::UpdateGoalsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment3::UpdateGoalsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Goals goals\n"
"\n"
"\n"
"================================================================================\n"
"MSG: assignment3/Goals\n"
"Goal[] primary_goals\n"
"Goal[] secondary_goals\n"
"\n"
"================================================================================\n"
"MSG: assignment3/Goal\n"
"string description\n"
"int32 priority\n"
"geometry_msgs/Point[] waypoints\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::assignment3::UpdateGoalsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment3::UpdateGoalsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goals);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UpdateGoalsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment3::UpdateGoalsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment3::UpdateGoalsResponse_<ContainerAllocator>& v)
  {
    s << indent << "goals: ";
    s << std::endl;
    Printer< ::assignment3::Goals_<ContainerAllocator> >::stream(s, indent + "  ", v.goals);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT3_MESSAGE_UPDATEGOALSRESPONSE_H
