// Generated by gencpp from file assignment3/UpdateGoals.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT3_MESSAGE_UPDATEGOALS_H
#define ASSIGNMENT3_MESSAGE_UPDATEGOALS_H

#include <ros/service_traits.h>


#include <assignment3/UpdateGoalsRequest.h>
#include <assignment3/UpdateGoalsResponse.h>


namespace assignment3
{

struct UpdateGoals
{

typedef UpdateGoalsRequest Request;
typedef UpdateGoalsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct UpdateGoals
} // namespace assignment3


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::assignment3::UpdateGoals > {
  static const char* value()
  {
    return "efc5b6996c038d80435f5da349a26d95";
  }

  static const char* value(const ::assignment3::UpdateGoals&) { return value(); }
};

template<>
struct DataType< ::assignment3::UpdateGoals > {
  static const char* value()
  {
    return "assignment3/UpdateGoals";
  }

  static const char* value(const ::assignment3::UpdateGoals&) { return value(); }
};


// service_traits::MD5Sum< ::assignment3::UpdateGoalsRequest> should match
// service_traits::MD5Sum< ::assignment3::UpdateGoals >
template<>
struct MD5Sum< ::assignment3::UpdateGoalsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::assignment3::UpdateGoals >::value();
  }
  static const char* value(const ::assignment3::UpdateGoalsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment3::UpdateGoalsRequest> should match
// service_traits::DataType< ::assignment3::UpdateGoals >
template<>
struct DataType< ::assignment3::UpdateGoalsRequest>
{
  static const char* value()
  {
    return DataType< ::assignment3::UpdateGoals >::value();
  }
  static const char* value(const ::assignment3::UpdateGoalsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::assignment3::UpdateGoalsResponse> should match
// service_traits::MD5Sum< ::assignment3::UpdateGoals >
template<>
struct MD5Sum< ::assignment3::UpdateGoalsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::assignment3::UpdateGoals >::value();
  }
  static const char* value(const ::assignment3::UpdateGoalsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment3::UpdateGoalsResponse> should match
// service_traits::DataType< ::assignment3::UpdateGoals >
template<>
struct DataType< ::assignment3::UpdateGoalsResponse>
{
  static const char* value()
  {
    return DataType< ::assignment3::UpdateGoals >::value();
  }
  static const char* value(const ::assignment3::UpdateGoalsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASSIGNMENT3_MESSAGE_UPDATEGOALS_H
