// Generated by gencpp from file assignment3/ValidatePlanResponse.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT3_MESSAGE_VALIDATEPLANRESPONSE_H
#define ASSIGNMENT3_MESSAGE_VALIDATEPLANRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignment3
{
template <class ContainerAllocator>
struct ValidatePlanResponse_
{
  typedef ValidatePlanResponse_<ContainerAllocator> Type;

  ValidatePlanResponse_()
    : valid(false)  {
    }
  ValidatePlanResponse_(const ContainerAllocator& _alloc)
    : valid(false)  {
  (void)_alloc;
    }



   typedef uint8_t _valid_type;
  _valid_type valid;





  typedef boost::shared_ptr< ::assignment3::ValidatePlanResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment3::ValidatePlanResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ValidatePlanResponse_

typedef ::assignment3::ValidatePlanResponse_<std::allocator<void> > ValidatePlanResponse;

typedef boost::shared_ptr< ::assignment3::ValidatePlanResponse > ValidatePlanResponsePtr;
typedef boost::shared_ptr< ::assignment3::ValidatePlanResponse const> ValidatePlanResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment3::ValidatePlanResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment3::ValidatePlanResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assignment3::ValidatePlanResponse_<ContainerAllocator1> & lhs, const ::assignment3::ValidatePlanResponse_<ContainerAllocator2> & rhs)
{
  return lhs.valid == rhs.valid;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assignment3::ValidatePlanResponse_<ContainerAllocator1> & lhs, const ::assignment3::ValidatePlanResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assignment3

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assignment3::ValidatePlanResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment3::ValidatePlanResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment3::ValidatePlanResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment3::ValidatePlanResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment3::ValidatePlanResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment3::ValidatePlanResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment3::ValidatePlanResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a04c5033e7efda95fc3786e8d449c6e7";
  }

  static const char* value(const ::assignment3::ValidatePlanResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa04c5033e7efda95ULL;
  static const uint64_t static_value2 = 0xfc3786e8d449c6e7ULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment3::ValidatePlanResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment3/ValidatePlanResponse";
  }

  static const char* value(const ::assignment3::ValidatePlanResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment3::ValidatePlanResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool valid\n"
"\n"
;
  }

  static const char* value(const ::assignment3::ValidatePlanResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment3::ValidatePlanResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.valid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ValidatePlanResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment3::ValidatePlanResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment3::ValidatePlanResponse_<ContainerAllocator>& v)
  {
    s << indent << "valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.valid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT3_MESSAGE_VALIDATEPLANRESPONSE_H
