// Generated by gencpp from file assignment3/ValidatePlan.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT3_MESSAGE_VALIDATEPLAN_H
#define ASSIGNMENT3_MESSAGE_VALIDATEPLAN_H

#include <ros/service_traits.h>


#include <assignment3/ValidatePlanRequest.h>
#include <assignment3/ValidatePlanResponse.h>


namespace assignment3
{

struct ValidatePlan
{

typedef ValidatePlanRequest Request;
typedef ValidatePlanResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ValidatePlan
} // namespace assignment3


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::assignment3::ValidatePlan > {
  static const char* value()
  {
    return "3d213886e8ff3dea48868fcfa2e522da";
  }

  static const char* value(const ::assignment3::ValidatePlan&) { return value(); }
};

template<>
struct DataType< ::assignment3::ValidatePlan > {
  static const char* value()
  {
    return "assignment3/ValidatePlan";
  }

  static const char* value(const ::assignment3::ValidatePlan&) { return value(); }
};


// service_traits::MD5Sum< ::assignment3::ValidatePlanRequest> should match
// service_traits::MD5Sum< ::assignment3::ValidatePlan >
template<>
struct MD5Sum< ::assignment3::ValidatePlanRequest>
{
  static const char* value()
  {
    return MD5Sum< ::assignment3::ValidatePlan >::value();
  }
  static const char* value(const ::assignment3::ValidatePlanRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment3::ValidatePlanRequest> should match
// service_traits::DataType< ::assignment3::ValidatePlan >
template<>
struct DataType< ::assignment3::ValidatePlanRequest>
{
  static const char* value()
  {
    return DataType< ::assignment3::ValidatePlan >::value();
  }
  static const char* value(const ::assignment3::ValidatePlanRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::assignment3::ValidatePlanResponse> should match
// service_traits::MD5Sum< ::assignment3::ValidatePlan >
template<>
struct MD5Sum< ::assignment3::ValidatePlanResponse>
{
  static const char* value()
  {
    return MD5Sum< ::assignment3::ValidatePlan >::value();
  }
  static const char* value(const ::assignment3::ValidatePlanResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment3::ValidatePlanResponse> should match
// service_traits::DataType< ::assignment3::ValidatePlan >
template<>
struct DataType< ::assignment3::ValidatePlanResponse>
{
  static const char* value()
  {
    return DataType< ::assignment3::ValidatePlan >::value();
  }
  static const char* value(const ::assignment3::ValidatePlanResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASSIGNMENT3_MESSAGE_VALIDATEPLAN_H
