// Generated by gencpp from file assignment3/ValidatePlanRequest.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT3_MESSAGE_VALIDATEPLANREQUEST_H
#define ASSIGNMENT3_MESSAGE_VALIDATEPLANREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <assignment3/Plan.h>
#include <assignment3/State.h>

namespace assignment3
{
template <class ContainerAllocator>
struct ValidatePlanRequest_
{
  typedef ValidatePlanRequest_<ContainerAllocator> Type;

  ValidatePlanRequest_()
    : plan()
    , state()  {
    }
  ValidatePlanRequest_(const ContainerAllocator& _alloc)
    : plan(_alloc)
    , state(_alloc)  {
  (void)_alloc;
    }



   typedef  ::assignment3::Plan_<ContainerAllocator>  _plan_type;
  _plan_type plan;

   typedef  ::assignment3::State_<ContainerAllocator>  _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::assignment3::ValidatePlanRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment3::ValidatePlanRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ValidatePlanRequest_

typedef ::assignment3::ValidatePlanRequest_<std::allocator<void> > ValidatePlanRequest;

typedef boost::shared_ptr< ::assignment3::ValidatePlanRequest > ValidatePlanRequestPtr;
typedef boost::shared_ptr< ::assignment3::ValidatePlanRequest const> ValidatePlanRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment3::ValidatePlanRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment3::ValidatePlanRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assignment3::ValidatePlanRequest_<ContainerAllocator1> & lhs, const ::assignment3::ValidatePlanRequest_<ContainerAllocator2> & rhs)
{
  return lhs.plan == rhs.plan &&
    lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assignment3::ValidatePlanRequest_<ContainerAllocator1> & lhs, const ::assignment3::ValidatePlanRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assignment3

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assignment3::ValidatePlanRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment3::ValidatePlanRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment3::ValidatePlanRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment3::ValidatePlanRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment3::ValidatePlanRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment3::ValidatePlanRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment3::ValidatePlanRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a860c6cf0d645e7b67a76e5881e4c512";
  }

  static const char* value(const ::assignment3::ValidatePlanRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa860c6cf0d645e7bULL;
  static const uint64_t static_value2 = 0x67a76e5881e4c512ULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment3::ValidatePlanRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment3/ValidatePlanRequest";
  }

  static const char* value(const ::assignment3::ValidatePlanRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment3::ValidatePlanRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Plan plan\n"
"State state\n"
"\n"
"================================================================================\n"
"MSG: assignment3/Plan\n"
"Waypoint[] waypoints\n"
"\n"
"================================================================================\n"
"MSG: assignment3/Waypoint\n"
"geometry_msgs/Point position\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: assignment3/State\n"
"geometry_msgs/Point current_position\n"
"Map environment_map\n"
"\n"
"================================================================================\n"
"MSG: assignment3/Map\n"
"geometry_msgs/Point[] obstacle_positions\n"
;
  }

  static const char* value(const ::assignment3::ValidatePlanRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment3::ValidatePlanRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.plan);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ValidatePlanRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment3::ValidatePlanRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment3::ValidatePlanRequest_<ContainerAllocator>& v)
  {
    s << indent << "plan: ";
    s << std::endl;
    Printer< ::assignment3::Plan_<ContainerAllocator> >::stream(s, indent + "  ", v.plan);
    s << indent << "state: ";
    s << std::endl;
    Printer< ::assignment3::State_<ContainerAllocator> >::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT3_MESSAGE_VALIDATEPLANREQUEST_H
