// Generated by gencpp from file assignment1_setup/ModelState.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT1_SETUP_MESSAGE_MODELSTATE_H
#define ASSIGNMENT1_SETUP_MESSAGE_MODELSTATE_H

#include <ros/service_traits.h>


#include <assignment1_setup/ModelStateRequest.h>
#include <assignment1_setup/ModelStateResponse.h>


namespace assignment1_setup
{

struct ModelState
{

typedef ModelStateRequest Request;
typedef ModelStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ModelState
} // namespace assignment1_setup


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::assignment1_setup::ModelState > {
  static const char* value()
  {
    return "62bdec03e9c27985cd2c0808e297c5db";
  }

  static const char* value(const ::assignment1_setup::ModelState&) { return value(); }
};

template<>
struct DataType< ::assignment1_setup::ModelState > {
  static const char* value()
  {
    return "assignment1_setup/ModelState";
  }

  static const char* value(const ::assignment1_setup::ModelState&) { return value(); }
};


// service_traits::MD5Sum< ::assignment1_setup::ModelStateRequest> should match
// service_traits::MD5Sum< ::assignment1_setup::ModelState >
template<>
struct MD5Sum< ::assignment1_setup::ModelStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::assignment1_setup::ModelState >::value();
  }
  static const char* value(const ::assignment1_setup::ModelStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment1_setup::ModelStateRequest> should match
// service_traits::DataType< ::assignment1_setup::ModelState >
template<>
struct DataType< ::assignment1_setup::ModelStateRequest>
{
  static const char* value()
  {
    return DataType< ::assignment1_setup::ModelState >::value();
  }
  static const char* value(const ::assignment1_setup::ModelStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::assignment1_setup::ModelStateResponse> should match
// service_traits::MD5Sum< ::assignment1_setup::ModelState >
template<>
struct MD5Sum< ::assignment1_setup::ModelStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::assignment1_setup::ModelState >::value();
  }
  static const char* value(const ::assignment1_setup::ModelStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment1_setup::ModelStateResponse> should match
// service_traits::DataType< ::assignment1_setup::ModelState >
template<>
struct DataType< ::assignment1_setup::ModelStateResponse>
{
  static const char* value()
  {
    return DataType< ::assignment1_setup::ModelState >::value();
  }
  static const char* value(const ::assignment1_setup::ModelStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASSIGNMENT1_SETUP_MESSAGE_MODELSTATE_H
