// Generated by gencpp from file assignment1_setup/ModelStateRequest.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT1_SETUP_MESSAGE_MODELSTATEREQUEST_H
#define ASSIGNMENT1_SETUP_MESSAGE_MODELSTATEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignment1_setup
{
template <class ContainerAllocator>
struct ModelStateRequest_
{
  typedef ModelStateRequest_<ContainerAllocator> Type;

  ModelStateRequest_()
    {
    }
  ModelStateRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::assignment1_setup::ModelStateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment1_setup::ModelStateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ModelStateRequest_

typedef ::assignment1_setup::ModelStateRequest_<std::allocator<void> > ModelStateRequest;

typedef boost::shared_ptr< ::assignment1_setup::ModelStateRequest > ModelStateRequestPtr;
typedef boost::shared_ptr< ::assignment1_setup::ModelStateRequest const> ModelStateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment1_setup::ModelStateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment1_setup::ModelStateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace assignment1_setup

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assignment1_setup::ModelStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment1_setup::ModelStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment1_setup::ModelStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment1_setup::ModelStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment1_setup::ModelStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment1_setup::ModelStateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment1_setup::ModelStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::assignment1_setup::ModelStateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment1_setup::ModelStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment1_setup/ModelStateRequest";
  }

  static const char* value(const ::assignment1_setup::ModelStateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment1_setup::ModelStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::assignment1_setup::ModelStateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment1_setup::ModelStateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ModelStateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment1_setup::ModelStateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::assignment1_setup::ModelStateRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT1_SETUP_MESSAGE_MODELSTATEREQUEST_H
